version: '3'

services:
  db:
    image: "mongo:4.0.10-xenial"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mydevelopmentsecret
      - MONGO_INITDB_DATABASE=blog
    volumes:
      - data:/data/db
      - configdb:/data/configdb
      - ./migrations/init.js:/docker-entrypoint-initdb.d/init.js:ro

  web:
    image: "node:10.16.0-stretch"
    environment:
      - PORT=3000
      - DB_URI=mongodb://root:mydevelopmentsecret@db:27017/
    volumes:
      - .:/opt/blog
    ports:
      - "3000:3000"
    working_dir: /opt/blog
    command: [ "npm", "start" ]

volumes:
  data:
  configdb:
