version: "3"

services:
  db:
    image: "mongo:4.0.10-xenial"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mydevelopmentsecret
      - MONGO_INITDB_DATABASE=blog
    volumes:
      - data:/data/db
      - configdb:/data/configdb
      - ./migrations/init.js:/docker-entrypoint-initdb.d/init.js:ro
    restart: unless-stopped

  web:
    image: "node:10.16.0-stretch"
    depends_on:
      - db
    environment:
      - PORT=3000
      - DB_SERVER_URI=mongodb://root:mydevelopmentsecret@db:27017/
      - DB_POOL_SIZE=20
      - DB_NAME=blog
    volumes:
      - .:/opt/blog
      - node-modules:/opt/blog/node_modules
    ports:
      - "3000:3000"
    restart: unless-stopped
    working_dir: /opt/blog
    command: npm run dev

volumes:
  data:
  configdb:
  node-modules:
